config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:index, :new, :create, :destroy]
      resources :likes, only: [:create]
      member do
        delete :destroy
      end
    end
  end

  # Remove the redundant resources :posts block
  resources :comments do
    member do
      delete :destroy
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "users#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :destroy, Post, author_id: user.id
      can :destroy, Comment, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, class_name: 'Post', foreign_key: :post_id
  belongs_to :user, class_name: 'User', foreign_key: :user_id

  validates :text, presence: true

  after_save :update_comments_counter
  after_destroy :update_comments_counter

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_like_counter

  def update_like_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  attribute :title, :string
  attribute :text, :text
  attribute :comments_counter, :integer, default: 0
  attribute :likes_counter, :integer, default: 0
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true

  after_save :update_post_counter
  after_destroy :update_post_counter

  def update_post_counter
    author.update(posts_counter: author.posts.count)
  end

  def recent_comments(limit = 3)
    comments.order(created_at: :desc).limit(limit)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :comments, dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy
  has_many :posts, foreign_key: :author_id, dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
  validates :role, inclusion: { in: %w[admin user], message: '%<value>s is not a valid role' }

  def recent_posts(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name bio posts_counter role])
  end

  def require_user
    redirect_to root_path unless @current_user
  end

  # attr_reader :current_user

  def index; end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_user_and_post

  def index
    @comments = @post.comments
  end

  def new
    @comment = current_user.comments.build
  end

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.post = @post

    if @comment.save
      redirect_to user_post_path(@user, @post), notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize! :destroy, @comment

    @comment.destroy
    redirect_to user_post_path(@user, @post), notice: 'Comment was successfully destroyed.'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def set_user_and_post
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @like = Like.new(user: @user, post: @post)

    if @like.save
      flash[:notice] = 'Like was successfully created.'
    else
      flash[:alert] = 'Failed to add like.'
    end

    redirect_to user_post_path(@user, @post)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user, only: %i[index show new create]
  before_action :set_post, only: %i[show destroy]

  def index
    @posts = @user.posts.includes(:comments)
  end

  def show
    @comments = @post.comments.includes(:user)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.comments_counter = 0
    @post.likes_counter = 0

    if @post.save
      redirect_to user_post_path(current_user, @post), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def destroy
    authorize! :destroy, @post

    @post.destroy
    redirect_to user_posts_path(current_user), notice: 'Post was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find_by(id: params[:user_id])

    return unless @user.nil?

    render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = current_user
    @users = User.all
  end

  def show
    if params[:id] == 'sign_out'
      sign_out(current_user)
      redirect_to new_user_session_path, notice: 'You have signed out.'
    else
      @user = User.find(params[:id])
      @user_posts = @user.posts
      @recent_posts = @user_posts.limit(3)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<div>
  <%= form_with(model: [@post, Comment.new], url: user_post_comments_path(@post.author, @post), local: true, html: { class: "myform" }) do |form| %>
    <div>
      Please enter comments here: <%= form.text_area :text %>
    </div>
    <div>
      <%= form.submit 'Submit' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1>calling from main</h1>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'style' %>

<div class="container">
<img src ='<%= @user.photo %>'  class="userImg" alt="User Photo">
<div class="userCon">
<h1 class="userName"><%= @user.name %> </h1>
<p class="Upostcount">Number of Posts: <%= @user.posts.count %></p>
</div>
</div>

<% @posts.each_with_index do |post, index| %>
   <div class="recPost postInt">
   <a class ="postclick" href="<%= user_post_path(@user, post) %>">
    <h2>Post #<%= index + 1 %></h2>
    
      <p class="pText" ><%= truncate(post.text, length: 50, separator: ' ') %></p>
    </a>
    <div class="comLik">
    <p>Comments: <%= post.comments.count %>, Likes: <%= post.likes.count %></p>
  </div>
  </div>

  <% if post.recent_comments.any? %>
  <div class="userCom">
  <% post.recent_comments.each do |comment| %>
            <% if comment.user.present? %>
              <p><%= comment.user.name %>: <%= comment.text %></p>
            <% else %>
              <p>Anonymous: <%= comment.text %></p>
            <% end %>
          <% end %>
  
  </div>
<% end %>
<% end %>

<button class="seeAllPostBtn">
<%= link_to 'Pagination', user_posts_path(@user.id) %>
</button>

app/views/posts/new.html.erb
<%= form_for :post, url: user_posts_path(@user) do |f| %>
  Post Title: <%= f.text_field :title %><br />
  Post Details: <%= f.text_area :text %><br />
  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<div class="recPost">
  <% if @post.present? %>
    <h2>Post #<%= @post.id %> by <%= @post.author&.name || 'Unknown Author' %></h2>
    <div class="comLik">
      <p class="postCom">Comments: <%= @post.comments.count %>, Likes: <%= @post.likes.count %></p>
    </div>
    <div class='userPost'>
      <p><%= @post.text %></p>
    </div>

    <div>
      <% if @post.author.present? %>
        <% if can? :destroy, @post %>
         <%= button_to 'Delete', user_post_path(@post.author, @post), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' } %>

        <% else %>
          <!-- Content for unauthorized users -->
          <p>You are not authorized to delete this post.</p>
        <% end %>
      <% else %>
        <!-- Handle the case where post author is nil (perhaps display an error message or take appropriate action) -->
        <p>Author not found for this post</p>
      <% end %>

      <%= link_to 'Add Comment', new_user_post_comment_path(@user, @post), class: 'commentBtn' %>

      <% @comments.each do |comment| %>
        <div class="comment-card">
          <% if comment.user.present? %>
            <p><strong><%= comment.user.name %>:</strong> <%= comment.text %></p>
            <% if can? :destroy, comment %>
              <%= button_to 'Delete Comment', user_post_comment_path(@user, @post, comment), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' } %>
            <% else %>
              <!-- Content for unauthorized users -->
              <p>You are not authorized to delete this comment.</p>
            <% end %>
          <% else %>
            <p><strong>Anonymous:</strong> <%= comment.text %></p>
          <% end %>
        </div>
      <% end %>
    </div>

    <h2>Comments</h2>
    <div class="userCom">
      <!-- Existing comments code -->
    </div>
  <% else %>
    <p>Post not found</p>
  <% end %>
</div>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'style' %>

<div >
  <% @users.each do |user| %>
    <a class="container"  href="<%= user_path(user.id) %>" >
      <img src ='<%= user.photo %>'  class="userImg" alt="User Photo">
      <div class="userCon">
        <h1 class="userName"><%= user.name %></h1>
        <p class="Upostcount">Number of posts: <%= user.posts.count %></p>
      </div>
    </a>
  <% end %>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'style' %>

<div class="container">
  <img src ='<%= @user.photo %>' class="userImg" alt="User Photo">
  <div class="userCon">
    <h1 class="userName"><%= @user.name %></h1>
    <p class="Upostcount"><strong>Number of Posts: <%= @user.posts.count %></strong></p>
  </div>
</div>

<div class="bio">
  <h1>Bio:</h1>
  <p class="bioText"><%= @user.bio %></p>
</div>

<% if @user.recent_posts.any? %>
  <% @user.recent_posts.each do |post| %>
    <div class="recPost">
      <h3><strong>Post: <%= post.title %></strong></h3>
      <p class="pText"><%= post.text %></p>
      <div class="comLik">
        <p><strong>Comments:</strong> <%= post.comments_counter %></p>
        <p><strong>Likes:</strong> <%= post.likes_counter %></p>
      </div>
    </div>
  <% end %>
<% end %>

<%= link_to "Add New Post", new_user_post_path(@user), class: "newPostBtn" %>

<button class="seeAllPostBtn">
  <%= link_to 'See all posts', user_posts_path(@user.id) %>
</button>